import React from "react";
import {
  LayoutDashboard,
  Receipt,
  Scale,
  Users,
  Package,
  Tag,
  Megaphone,
  CreditCard,
  Webhook,
  Layers,
  Mail,
  MailCheck,
  Languages,
  BookOpen,
  ShieldCheck,
  FolderTree,
  Folder,
  FolderOpen,
  Menu,
  Globe,
  Settings,
  KeyRound,
  UserCog,
  Lock,
  AppWindow,
  ShoppingBag,
  Database,
  BarChart3,
  Bell,
  BellRing,
  Cloud,
  Code2,
  Cpu,
  Crown,
  FileSpreadsheet,
  FileText,
  Heart,
  Home,
  Info,
  List,
  MessageSquare,
  Monitor,
  PieChart,
  PlusCircle,
  RefreshCw,
  Rocket,
  Send,
  Server,
  Shield,
  SlidersHorizontal,
  Star,
  Sun,
  Terminal,
  Timer,
  TrendingUp,
  Truck,
  Wrench,
  Zap,
  Search,
  type LucideIcon,
} from "lucide-react";

/** 图标名称 -> 组件 注册表（菜单树节点图标统一从这里解析） */
export const MENU_ICON_REGISTRY: Record<string, LucideIcon> = {
  LayoutDashboard,
  Receipt,
  Scale,
  Users,
  Package,
  Tag,
  Megaphone,
  CreditCard,
  Webhook,
  Layers,
  Mail,
  MailCheck,
  Languages,
  BookOpen,
  ShieldCheck,
  FolderTree,
  Folder,
  FolderOpen,
  Menu,
  Globe,
  Settings,
  KeyRound,
  UserCog,
  Lock,
  AppWindow,
  ShoppingBag,
  Database,
  BarChart3,
  Bell,
  BellRing,
  Cloud,
  Code2,
  Cpu,
  Crown,
  FileSpreadsheet,
  FileText,
  Heart,
  Home,
  Info,
  List,
  MessageSquare,
  Monitor,
  PieChart,
  PlusCircle,
  RefreshCw,
  Rocket,
  Send,
  Server,
  Shield,
  SlidersHorizontal,
  Star,
  Sun,
  Terminal,
  Timer,
  TrendingUp,
  Truck,
  Wrench,
  Zap,
  Search,
};

/** 图标选择器候选列表（中文语义标签） */
export const ICON_OPTIONS: { name: string; label: string }[] = [
  { name: "LayoutDashboard", label: "概览看板" },
  { name: "Receipt", label: "交易流水" },
  { name: "Scale", label: "对账中心" },
  { name: "Users", label: "用户管理" },
  { name: "UserCog", label: "系统用户" },
  { name: "Package", label: "商品配置" },
  { name: "ShoppingBag", label: "商城购物" },
  { name: "Tag", label: "折扣优惠" },
  { name: "Megaphone", label: "营销推广" },
  { name: "CreditCard", label: "支付渠道" },
  { name: "Webhook", label: "网关回调" },
  { name: "Layers", label: "接入应用" },
  { name: "Mail", label: "邮件通道" },
  { name: "MailCheck", label: "邮件回执" },
  { name: "Languages", label: "多语言" },
  { name: "BookOpen", label: "字典管理" },
  { name: "ShieldCheck", label: "角色权限" },
  { name: "KeyRound", label: "权限管理" },
  { name: "FolderTree", label: "菜单目录" },
  { name: "Folder", label: "分类目录" },
  { name: "FolderOpen", label: "展开目录" },
  { name: "Globe", label: "全球网络" },
  { name: "Settings", label: "系统设置" },
  { name: "Lock", label: "安全锁定" },
  { name: "AppWindow", label: "应用窗口" },
  { name: "Database", label: "数据存储" },
  { name: "BarChart3", label: "数据图表" },
  { name: "Bell", label: "通知提醒" },
  { name: "Cloud", label: "云端服务" },
  { name: "Code2", label: "代码开发" },
  { name: "Cpu", label: "计算资源" },
  { name: "Crown", label: "超级管理" },
  { name: "FileSpreadsheet", label: "财务报表" },
  { name: "FileText", label: "文档报表" },
  { name: "Home", label: "首页" },
  { name: "List", label: "清单列表" },
  { name: "MessageSquare", label: "消息沟通" },
  { name: "Monitor", label: "监控大屏" },
  { name: "PieChart", label: "占比统计" },
  { name: "PlusCircle", label: "新增" },
  { name: "RefreshCw", label: "刷新同步" },
  { name: "Rocket", label: "快速上线" },
  { name: "Send", label: "发送" },
  { name: "Server", label: "服务器" },
  { name: "Shield", label: "安全防护" },
  { name: "SlidersHorizontal", label: "参数调节" },
  { name: "Star", label: "星标收藏" },
  { name: "Sun", label: "日间模式" },
  { name: "Terminal", label: "终端命令" },
  { name: "Timer", label: "定时任务" },
  { name: "TrendingUp", label: "增长趋势" },
  { name: "Truck", label: "物流配送" },
  { name: "Wrench", label: "工具维护" },
  { name: "Zap", label: "闪电效率" },
];

/** 根据图标名称渲染图标组件（找不到时回退为 Menu） */
export const renderMenuIcon = (iconName: string, className?: string): React.ReactNode => {
  const Icon = MENU_ICON_REGISTRY[iconName] || Menu;
  return <Icon className={className} />;
};
